export const GET_MENU_REQUEST = 'GET_MENU_REQUEST'
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS'
export const GET_MENU_FAIL = 'GET_MENU_FAIL'


export const GET_HOTEL_REQUEST = 'GET_HOTEL_REQUEST'
export const GET_HOTEL_SUCCESS = 'GET_HOTEL_SUCCESS'
export const GET_HOTEL_FAIL = 'GET_HOTEL_FAIL'



export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL'


export const GET_PRODUCT_ONE_REQUEST = 'GET_PRODUCT_ONE_REQUEST'
export const GET_PRODUCT_ONE_SUCCESS = 'GET_PRODUCT_ONE_SUCCESS'
export const GET_PRODUCT_ONE_FAIL = 'GET_PRODUCT_ONE_FAIL'



export const GET_SINGLE_HOTEL_REQUEST = 'GET_SINGLE_HOTEL_REQUEST'
export const GET_SINGLE_HOTEL_SUCCESS = 'GET_SINGLE_HOTEL_SUCCESS'
export const GET_SINGLE_HOTEL_FAIL = 'GET_SINGLE_HOTEL_FAIL'