// export const ADD_TO_CART = 'ADD_TO_CART'
// export const ADD_QUANTITY = 'ADD_QUANTITY'
// export const REMOVE_ITEM = 'REMOVE_ITEM'
// export const SUB_QUANTITY = 'SUB_QUANTITY'





export const  GET_TO_CART_REQUEST = "GET_TO_CART_REQUEST"

export const  GET_TO_CART_SUCCESS = "GET_TO_CART_SUCCESS"
export const  GET_TO_CART_FAIL = "GET_TO_CART_FAIL"
export const  ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"

export const  ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const  ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL"
export const  ADD_QUANTITY = "ADD_QUANTITY"
export const  SUB_QUANTITY = "SUB_QUANTITY"
export const  CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS"
export const  CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD"
 export const  ADD_TO_EXTRACART_SUCCESS = "ADD_TO_EXTRACART_SUCCESS"
 
 export const DELETE_ITEM = "DELETE_ITEM"
