export const GET_EXTRACAT_REQUEST = 'GET_EXTRACAT_REQUEST'
export const GET_EXTRACAT_SUCCESS = 'GET_EXTRACAT_SUCCESS'
export const GET_EXTRACAT_FAIL = 'GET_EXTRACAT_FAIL'

export const GET_EXTRAPRO_REQUEST = 'GET_EXTRAPRO_REQUEST'
export const GET_EXTRAPRO_SUCCESS = 'GET_EXTRAPRO_SUCCESS'
export const GET_EXTRAPRO_FAIL = 'GET_EXTRACAT_FAIL'

